twig:
    default_path: '%kernel.project_dir%/templates'
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    globals:
        assets_url: "%assets_url%"
        google_maps_frontend_api_key: "%google_maps_frontend_api_key%"
